[project]
name = "dqn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "gymnasium[all]>=1.1.1",
    "matplotlib>=3.9.4",
    "numpy>=2.0.2",
    "torch>=2.8.0",
    "torchvision>=0.23.0",
]
